name: Run main.py every day at 10PM

on:
  schedule:
    - cron: '0 13 * * *'  # UTC 기준 (10PM KST = 1PM UTC)

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'  # 원하는 파이썬 버전 명시 (예: '3.10')

    - name: Install dependencies
      run: |
        pip install -r requirements.txt  # 필요시

    - name: Run main.py
      run: |
        python main.py
